baseurl = "https://webdemosite.github.io/museum/"
# baseurl = "https://casaldecultura.github.io"
languageCode = "es"
defaultContentLanguage = "es"
title = "Casal de Cultura"
theme = ["dream", "darths-hugo-shortcodes", "hugo-easy-gallery"]

# ignore stupid error
ignoreErrors = ["error-missing-instagram-accesstoken", "error-remote-getjson", "error-disable-taxonomy"]

# (optional) disable tags and categories
disableKinds = ["taxonomy", "term"]

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

# recommended for GitHub pages
publishDir = 'docs'

# enable inline html rendering within Markdown posts
[markup.goldmark.renderer] 
unsafe = true 



[params]
  background = "#f7f7f7"
  backgroundImage = "/img/Soller_DSCF1080_compressed.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  # darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  author = "Ensenyat"
  description = "El mejor museo en Mallorca!"
  avatar = "/img/avatar.png"
  # roundAvatar = true
  sizeAvatar = "medium" # values: tiny, small (default), medium, large, huge
  headerTitle = "Casal de Cultura"
  motto = "Museo de Sóller y centro <br> de eventos culturales"
  hideArticleTags = "true"
  maxTags = 0
  simple = true # hide tags, categories, archive EVERYWHERE
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = false
  # rssHeader = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  # socials, deprecated - use /data/socials.toml instead
  # email = "casaldecultura@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""
  
  # Add IndieAuth endpoint here, as per https://indieweb.org/IndieAuth#How_to
  # indieauth = "https://indieauth.com/auth"

  siteStartYear = 2023
  # Required for "Site last updated" footer
  commit = "https://github.com/museo/casaldecultura.github.io/commits/"

  favicon = "/favicons/favicon.ico"

  # true: load 3rd-party JS/CSS from CDN; false: load instead from local files
	CDNJS = false
  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsCDN = "js/3p/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = false
  # topTags = true
  textButtons = true
  textButtonsMini = true
  textSocials = true
  
  # Error 404 Not Found page text
  error404Header = "Error 404"
  error404SubHeader = "Pagina no encontrada. Por favor haga clic aqui para volver al inicio."
  
  # Enable/Disable Mac OS X style scrollbars - GLITCHY! Recommended false if using PhotoSwipe
  OverlayScrollbars = false

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  reversePostAndAside = true
  shareInAside = true
  fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true
  # disableFlip = true
  hideBackSocialLinks = false

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
  
    [params.advanced]
    customCSS = ["css/custom.css"] # files in the list will be loaded in order
  
  # required for search
  # [outputs]
  #   home = ["HTML", "RSS", "JSON"]